- name: Deploy to AWS EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 Instance
      ec2_instance:
        instance_type: t2.medium
        tags:
          Name: "eShop_production"
          Created: "{{ ansible_date_time.epoch }}"
        image_id: ami-0230bd60aa48260c6
        region: us-east-1
        key_name: ansible
        vpc_subnet_id: subnet-023f54cb0099708a1
        count: 1
        network:
          assign_public_ip: yes
        wait: yes
        security_group: eshop
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ session_token }}"
      register: ec2_instance_result