name: Build and test eshop workflowd

on:
  workflow_dispatch:
  push:

jobs: 
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.SEMESTRALKA_WORKFLOW_TOKEN }} # `GH_PAT` is a secret that contains your PAT

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14

      - name: Cache 
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package.lock.json') }}
          restore-keys: node_modules-

      - name: Install packages with npm
        run: |
          npm ci
        
  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.SEMESTRALKA_WORKFLOW_TOKEN }} # `GH_PAT` is a secret that contains your PAT

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14

      - name: Cache node module
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package.lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

      - name: Cache node modules and build folder
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os }}-build-${{ github.run_id }} 
          restore-keys: ${{ runner.os }}-build-${{ github.run_id }}

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.SEMESTRALKA_WORKFLOW_TOKEN }} # `GH_PAT` is a secret that contains your PAT

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14

      - name: Cache 
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package.lock.json') }}

      - name: Run tests
        run: |
          npm run test -- --colors          
  
  Deploy:
      needs: [Build, Test]
      if: ${{github.ref == 'refs/heads/main'}}
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.1

        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install Ansible
          run: sudo pip3 install ansible

        - name: Install Boto3 & Boto
          run: sudo pip3 install boto3 boto 
        
        - name: Deploy with Ansible
          env:
            ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
          run: |
            echo "${{secrets.SEMESTRALKA}}" > ansible.pem
            chmod 400 ansible.pem
            sudo ansible-playbook ansible/playbook.yml --user ec2-user --key-file ansible.pem -e "access_key=${ACCESS_KEY}" -e "secret_key=${SECRET_KEY}" -e "session_token=${SESSION_TOKEN}"
            rm ansible.pem
